In [2]:
import numpy as np

### *Latihan* ###

In [3]:
# 1. Buatlah Array dengan output sebagai berikut
np.ones(10, dtype='int64')*5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int64)

In [4]:
np.array([range(i, i+4) for i in [2, 6, 10, 14]]) #List comprehensif

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [5]:
# 2. Buatlah Array dengan output sebagai berikut:
np.array([range(i, i+3) for i in [1, 3, 5]])

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [6]:
# 3. Buatlah program python yang dapat memutar balikan array 3x3 sebgai berikut:
array1 = np.array([range(i, i+3) for i in [1, 4, 7]])
awal = np.arange(1,10).reshape(3,3)
awal

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Expected output hint: index slicing pada row dan column
array1 = np.array([range(i, i+3) for i in [1, 4, 7]])
print(array1[::-1])
awal[::-1,::-1]

[[7 8 9]
 [4 5 6]
 [1 2 3]]


array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [8]:
# 4. Buat seperti soal no dua dengan function:
def buat_matriks():
    angka = int(input('Masukkan angka: '))
    hasil = np.array([range(i, i+3) for i in [angka, angka+2, angka+4]])
    return hasil

In [9]:
# cara kedua:
def cara_kedua():
    angka = int(input('Masukkan angka: '))
    row1 = np.arange(angka, angka+3)
    row2 = np.arange(row1[-1], row1[-1]+3)
    row3 = np.arange(row2[-1], row2[-1]+3)
    hasil = np.vstack((np.vstack((row1, row2)), row3))
    return hasil

In [10]:
buat_matriks()

Masukkan angka: 1


array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])